### PR TITLE
Adds command line support

### LINKED ISSUE #14: Support for command line arguments
Just throwing some ideas out there:

- `--log-level LEVEL` / `--verbose` / `-v` / `--quiet` / `-q`
- `--token-file FILE` / `-t FILE`
- `--channels=list,of,authorized,channels`
- `--channel-file FILE`
- `--prices-file`
- `--fossils-file`

etc...

### PR DESCRIPTION
**Pull request by lexicalunit**
Resolves #14

### CODE REVIEW

**Comment by lexicalunit** [comment]
This is a pretty big change but I think it simplifies a lot of things and makes the tests easier so we don't have to rely on monkeypatch nearly as much. It'd be nice to get rid of almost all of that. Yay dependency injection!

**Comment by lexicalunit** [comment]
Also I would have been terrified to make such a big change like this without tests. Seeing them pass after all this refactoring was 😗👌

**Comment by theastropath** [comment]
At first glance I was fairly certain the tests were going to leave behind the backup files afterwards, but then I saw that you based the backup location off of the path of the prices file.  Good stuff!

**Comment by theastropath** [comment]
Without specifying any command-line parameters, it looks like turbot no longer is accepting commands.  I'm investigating a bit, but it looked like the defaults were supposed to be the same as before...

**Comment by lexicalunit** [comment]
Oh oops, I see the bug. One sec.

**Comment by theastropath** [comment]
Assuming you found the same bug I did, line 852, where you made the list of auth_channels?  By default it ended up as a list inside a list.  Need to add the get_channels with the [*channels]

**Comment by lexicalunit** [comment]
Yeah it should be:

```
auth_channels = get_channels(auth_channels_file) + list(channel)
```

**Comment by lexicalunit** [comment]
https://github.com/theastropath/turbot/pull/39

**Pull request merged**
